const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.DragnDrop,
		C3.Behaviors.Pin,
		C3.Plugins.Text,
		C3.Plugins.TextBox,
		C3.Plugins.Keyboard,
		C3.Plugins.Mouse,
		C3.Plugins.Button,
		C3.Behaviors.solid,
		C3.Behaviors.Platform,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.TextBox.Cnds.CompareText,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Behaviors.DragnDrop.Acts.SetEnabled,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.TextBox.Acts.SetEnabled,
		C3.Plugins.Sprite.Cnds.IsOverlappingOffset,
		C3.Behaviors.Pin.Acts.PinByImagePoint,
		C3.Plugins.Text.Cnds.CompareText,
		C3.Plugins.TextBox.Acts.Destroy,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Text.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Button.Acts.SetVisible,
		C3.Plugins.Button.Acts.SetEnabled,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Behaviors.Platform.Cnds.OnStop,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.Sprite.Cnds.IsOutsideLayout,
		C3.Plugins.System.Acts.RestartLayout
	];
};
self.C3_JsPropNameTable = [
	{ATX_Case: 0},
	{ArrastrarYSoltar: 0},
	{Pegado: 0},
	{cpu: 0},
	{cpu_cooler: 0},
	{Grafica: 0},
	{Placa_base: 0},
	{psu: 0},
	{ram: 0},
	{Texto: 0},
	{EntradaDeTexto_PlacaBase: 0},
	{EntradaDeTexto_PSU: 0},
	{EntradaDeTexto_RAM: 0},
	{EntradaDeTexto_CoolerCPU: 0},
	{EntradaDeTexto_CPU: 0},
	{EntradaDeTexto_Grafica: 0},
	{Teclado: 0},
	{Mouse: 0},
	{psu2: 0},
	{Texto2: 0},
	{Texto3: 0},
	{Sprite: 0},
	{win: 0},
	{siguienteNivel: 0},
	{Botón: 0},
	{Sólido: 0},
	{Tile_: 0},
	{Tile_2: 0},
	{Tile_3: 0},
	{Sprite2: 0},
	{Sprite3: 0},
	{Sprite4: 0},
	{Sprite5: 0},
	{Sprite6: 0},
	{Tile_4: 0},
	{Tile_5: 0},
	{Tile_6: 0},
	{Plataforma: 0},
	{Sprite7: 0},
	{Sprite8: 0},
	{Sprite9: 0},
	{lightpinkabstractbackgroundvector: 0},
	{win2: 0},
	{Aciertos: 0},
	{llave: 0}
];

self.InstanceType = {
	ATX_Case: class extends self.ISpriteInstance {},
	cpu: class extends self.ISpriteInstance {},
	cpu_cooler: class extends self.ISpriteInstance {},
	Grafica: class extends self.ISpriteInstance {},
	Placa_base: class extends self.ISpriteInstance {},
	psu: class extends self.ISpriteInstance {},
	ram: class extends self.ISpriteInstance {},
	Texto: class extends self.ITextInstance {},
	EntradaDeTexto_PlacaBase: class extends self.ITextInputInstance {},
	EntradaDeTexto_PSU: class extends self.ITextInputInstance {},
	EntradaDeTexto_RAM: class extends self.ITextInputInstance {},
	EntradaDeTexto_CoolerCPU: class extends self.ITextInputInstance {},
	EntradaDeTexto_CPU: class extends self.ITextInputInstance {},
	EntradaDeTexto_Grafica: class extends self.ITextInputInstance {},
	Teclado: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	psu2: class extends self.ISpriteInstance {},
	Texto2: class extends self.ITextInstance {},
	Texto3: class extends self.ITextInstance {},
	Sprite: class extends self.ISpriteInstance {},
	win: class extends self.ISpriteInstance {},
	siguienteNivel: class extends self.ISpriteInstance {},
	Botón: class extends self.IButtonInstance {},
	Tile_: class extends self.ISpriteInstance {},
	Tile_2: class extends self.ISpriteInstance {},
	Tile_3: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Tile_4: class extends self.ISpriteInstance {},
	Tile_5: class extends self.ISpriteInstance {},
	Tile_6: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	lightpinkabstractbackgroundvector: class extends self.ISpriteInstance {},
	win2: class extends self.ISpriteInstance {}
}